### ISSUE TITLE
Changed API ?

### ISSUE THREAD

**Issue by Mob19** [STATWORX/covid-19-api#1]
Has something changed in your API names /address or ahem you closed it? 

This code worked fine up until June 16th.

> library(httr)
> library(jsonlite)
> 
> # Post to API
> response <- httr::GET(url = "https://api.statworx.com/covid", encode = "json")
> 
> # Convert to data frame
> content <- rawToChar(response$content)
> df <- data.frame(fromJSON(content))
### Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^

**Comment by sebastianheinz** [comment]
It seems that our data providing service from ECDC is down since the weekend. We will contact them. I will keep you posted.

**Comment by Mob19** [comment]
Hi Sebastian,

 

Thank you very much for the feedback.

 

And thank you very much for your code (https://www.r-bloggers.com/making-of-a-free-api-for-covid-19-data/).  

 

I made a few modifications to the graphing and I and my friends have become dependent on it to give us a quick daily view of how things are progressing.  

 

Best regards,

 

Mike O’Brien,

**Comment by sebastianheinz** [comment]
Hi Mike,

the API shold now work again as expected. ECDC had problems with their data ingestion but fixed it.

Best,
Sebastian

**Comment by Mob19** [comment]
Excellent.  Thank you very much.

 

Regards,

 

Mike O’Brien
